FROM --platform=${BUILDPLATFORM} node:24 AS build

WORKDIR /opt/node_app

COPY . .

RUN --mount=type=cache,target=/root/.cache/yarn \
    npm_config_target_arch=${TARGETARCH} yarn --network-timeout 600000

ARG NODE_ENV=production
ARG VITE_APP_ENABLE_BACKEND_AUTH
ARG VITE_APP_AUTH_BACKEND
ARG VITE_APP_HTTP_STORAGE_BACKEND_URL
ARG VITE_APP_AI_BACKEND
ARG VITE_APP_WS_SERVER_URL
ARG VITE_APP_PLUS_APP
ARG VITE_APP_PLUS_LP

ENV NODE_ENV=${NODE_ENV}
ENV VITE_APP_ENABLE_BACKEND_AUTH=${VITE_APP_ENABLE_BACKEND_AUTH}
ENV VITE_APP_AUTH_BACKEND=${VITE_APP_AUTH_BACKEND}
ENV VITE_APP_HTTP_STORAGE_BACKEND_URL=${VITE_APP_HTTP_STORAGE_BACKEND_URL}
ENV VITE_APP_AI_BACKEND=${VITE_APP_AI_BACKEND}
ENV VITE_APP_WS_SERVER_URL=${VITE_APP_WS_SERVER_URL}
ENV VITE_APP_PLUS_APP=${VITE_APP_PLUS_APP}
ENV VITE_APP_PLUS_LP=${VITE_APP_PLUS_LP}

RUN npm_config_target_arch=${TARGETARCH} yarn build:app:docker

FROM --platform=${TARGETPLATFORM} nginx:1.27-alpine

COPY --from=build /opt/node_app/excalidraw-app/build /usr/share/nginx/html

HEALTHCHECK CMD wget -q -O /dev/null http://localhost || exit 1